function TMSSVCIDP = importIDP(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  TMSSVCIDP = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  TMSSVCIDP = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  TMSSVCIDP = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  TMSSVCIDP = importfile("/Users/mttread/Documents/ANALYSES/RCDC_Modeling/TMS_Modeling/TMS/TMS_SVC_IDP.xlsx", "TMS_SPSS", [2, 3201]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Jan-2021 13:48:00

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 3201];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 23);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":W" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["subj", "run", "runstart", "trial", "Cue1_Onset", "Cue2_Onset", "response", "Reward", "Effort", "Order", "RT", "Trigger", "ITI_Onset", "ITI_Offset", "CounterBalance", "Site", "IDP", "IDP_binary", "RunCheck", "SVC", "RunCheck_1", "IDP_signed", "SVH"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
TMSSVCIDP = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":W" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    TMSSVCIDP = [TMSSVCIDP; tb]; %#ok<AGROW>
end

%% Convert to output type
TMSSVCIDP = table2array(TMSSVCIDP);
end